"""Build a transparent Kaggriculture submission from a tested route module.

The output intentionally stores strategy tables as normal Python literals.
There is no compression, encoding, dynamic evaluation, or generated bytecode in
the submission.  Keeping this builder separate makes route experiments
repeatable while leaving ``main.py`` directly inspectable by humans.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib.util
import json
import pprint
from pathlib import Path


ROOT = Path(__file__).resolve().parent


COMPLETE_ACTION_ENGINE = r'''
# The complete command vocabulary is kept explicit.  The opening book is the
# principal variation; this generator is the recovery/search frontier whenever
# a stochastic board event makes the principal variation unusable.
_DIRECTIONS = ("NORTH", "SOUTH", "EAST", "WEST")
_CROPS = ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON")
_ANIMALS = ("GOOSE", "COW", "SHEEP")
_PRODUCTS = ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON",
             "EGG", "MILK", "WOOL", "FERTILIZER")


def _legal_unit_actions(obs, actor_index):
    """Generate every contextually legal command for one worker.

    Movement is always accepted by the simulator (an edge move is a no-op), so
    all four directions remain in the legal frontier.  Resource actions are
    emitted only when the public/private state shows they can have an effect.
    """
    _seat, farm = _farm(obs)
    private = _get(obs, "private", {}) or {}
    positions = [_get(farm, "farmer", [0, 0]), *list(_get(farm, "hands", []) or [])]
    inventories = list(_get(private, "inventories", []) or [])
    if actor_index >= len(positions):
        return [["PASS"]]
    position = positions[actor_index]
    inventory = dict(inventories[actor_index] or {}) if actor_index < len(inventories) else {}
    seeds = dict(_get(private, "seeds", {}) or {})
    shed = dict(_get(private, "shed", {}) or {})
    tile = _tile_at(farm, position)
    actions = [["PASS"], *[[direction] for direction in _DIRECTIONS]]

    if tile is None:
        actions.extend([["BUILD_COOP"], ["BUILD_PASTURE"]])
        actions.extend([["PLANT", crop] for crop in _CROPS if int(seeds.get(crop, 0) or 0) > 0])
    elif isinstance(tile, dict):
        kind = str(tile.get("kind", "")).upper()
        animal = str(tile.get("animal", "")).upper()
        if kind == "WEED":
            actions.append(["DIG"])
        elif kind == "PLANT":
            actions.append(["DIG"])
            if not tile.get("watered_today", False):
                actions.append(["WATER"])
            if int(inventory.get("FERTILIZER", 0) or 0) > 0:
                actions.append(["FERTILIZE"])
            if int(tile.get("yield_units", 0) or 0) > 0:
                actions.append(["HARVEST"])
        elif kind in ("COOP", "PASTURE"):
            if animal:
                if not tile.get("cared_today", False):
                    actions.append(["CARE"])
                if not tile.get("fed_today", False) and int(inventory.get("WHEAT", 0) or 0) > 0:
                    actions.append(["FEED"])
                if int(tile.get("yield_units", 0) or 0) > 0:
                    actions.append(["HARVEST"])
                if tile.get("fertilizer_available", False):
                    actions.append(["COLLECT_FERTILIZER"])
            else:
                actions.append(["DIG"])
                compatible = ("GOOSE",) if kind == "COOP" else ("COW", "SHEEP")
                actions.extend([["PLACE", item, 1] for item in compatible
                                if int(inventory.get(item, 0) or 0) > 0])

    tiles = list(_get(farm, "tiles", []) or [])
    try:
        adjacent = (int(position[0]), int(position[1])) in _shed_access(len(tiles) or 10)
    except (TypeError, ValueError, IndexError):
        adjacent = False
    if adjacent:
        if any(int(value or 0) > 0 for value in inventory.values()):
            actions.append(["DROP"])
        actions.extend([["PICKUP", item, int(quantity)] for item, quantity in shed.items()
                        if int(quantity or 0) > 0])
        actions.extend([["PLACE", item, int(quantity)] for item, quantity in inventory.items()
                        if int(quantity or 0) > 0])
    return actions


def _legal_market_orders(obs):
    """Generate the complete one-order market frontier for search/recovery."""
    _seat, farm = _farm(obs)
    private = _get(obs, "private", {}) or {}
    shed = dict(_get(private, "shed", {}) or {})
    orders = []
    orders.extend([["BUY_SEED", crop, 1] for crop in _CROPS])
    orders.extend([["BUY_ANIMAL", animal, 1] for animal in _ANIMALS])
    orders.extend([["BUY_PRODUCT", item, 1] for item in ("WHEAT", "FERTILIZER")])
    orders.extend([["SELL", item, int(shed.get(item, 0) or 0)] for item in _PRODUCTS
                   if int(shed.get(item, 0) or 0) > 0])
    orders.append(["HIRE"])
    if len(_get(farm, "unlocked_quadrants", []) or []) < 4:
        orders.append(["BUY_LAND"])
    return orders


def _recovery_agent(obs):
    """Choose survival-first moves if the principal evaluator ever raises."""
    _seat, farm = _farm(obs)
    unit_count = 1 + len(_get(farm, "hands", []) or [])
    priorities = {
        "FEED": 100, "WATER": 95, "HARVEST": 85,
        "COLLECT_FERTILIZER": 75, "CARE": 65, "DIG": 45,
        "DROP": 35, "PASS": 0,
    }
    chosen = []
    for actor_index in range(unit_count):
        legal = _legal_unit_actions(obs, actor_index)
        chosen.append(max(legal, key=lambda row: priorities.get(row[0], 5)))
    action = {"farmer": chosen[0], "hands": chosen[1:], "market": []}
    if _step(obs) == len(_ACTIONS) - 1:
        action = _terminal_market(obs, action)
    return action
'''


def load_module(path: Path):
    spec = importlib.util.spec_from_file_location("readable_route_source", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import route source: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _read_route(path: Path) -> dict:
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def build(
    source: Path,
    destination: Path,
    unit_source: Path | None = None,
    all_product_preempt: bool = False,
    alternate_source: Path | None = None,
    threat_source: Path | None = None,
    hazard_source: Path | None = None,
) -> None:
    if source.name.endswith(".json.gz"):
        payload = _read_route(source)
        actions = payload["actions"]
        if unit_source is not None:
            unit_actions = _read_route(unit_source)["actions"]
            if len(unit_actions) != len(actions):
                raise RuntimeError("Market and worker routes have different lengths")
            actions = [
                {
                    "farmer": row_units.get("farmer", ["PASS"]),
                    "hands": row_units.get("hands", []),
                    "market": row_market.get("market", []),
                }
                for row_market, row_units in zip(actions, unit_actions)
            ]
        canonical = json.dumps(actions, separators=(",", ":"), sort_keys=True).encode("utf-8")
        route_hash = hashlib.sha256(canonical).hexdigest()
        # Route files contain data only.  Reuse the tested readable recovery and
        # market implementation, but never its encoded action data.
        logic_source = ROOT / "v14_route_x_r3.py"
        module = load_module(logic_source)
        source_text = logic_source.read_text(encoding="utf-8")
    else:
        module = load_module(source)
        actions = module._ACTIONS
        route_hash = module._ROUTE_ACTION_SHA256
        source_text = source.read_text(encoding="utf-8")

    alternate_actions = None
    alternate_hash = None
    if alternate_source is not None:
        alternate_payload = _read_route(alternate_source)
        alternate_actions = alternate_payload["actions"]
        if len(alternate_actions) != len(actions):
            raise RuntimeError("Primary and alternate routes have different lengths")
        alternate_canonical = json.dumps(
            alternate_actions, separators=(",", ":"), sort_keys=True
        ).encode("utf-8")
        alternate_hash = hashlib.sha256(alternate_canonical).hexdigest()

    threat_markets = None
    if threat_source is not None:
        threat_payload = _read_route(threat_source)
        threat_actions = threat_payload["actions"]
        if len(threat_actions) != len(actions):
            raise RuntimeError("Strategy and threat routes have different lengths")
        threat_markets = [row.get("market", []) for row in threat_actions]
    hazard_model = module._GOLD_HAZARD
    if hazard_source is not None:
        hazard_actions = _read_route(hazard_source)["actions"]
        if len(hazard_actions) != len(actions):
            raise RuntimeError("Strategy and hazard routes have different lengths")
        hazard_model = {}
        for step, action in enumerate(hazard_actions):
            quantities = {}
            for order in action.get("market", []) or []:
                if len(order) >= 3 and order[0] == "SELL":
                    item = order[1]
                    quantities[item] = quantities.get(item, 0) + max(0, int(order[2]))
            if quantities:
                hazard_model[str(step)] = [
                    [item, 1.0, float(quantity), 1]
                    for item, quantity in quantities.items()
                ]
    marker = "_WEED_REPLAY_STEPS ="
    marker_at = source_text.index(marker)
    readable_logic = source_text[marker_at:]
    if all_product_preempt:
        readable_logic = readable_logic.replace("_PREEMPT_MAX_BATCH = 30", "_PREEMPT_MAX_BATCH = 100")
        readable_logic = readable_logic.replace("_PREEMPT_STOP = 680", "_PREEMPT_STOP = 719")
        readable_logic = readable_logic.replace(
            '_PREMIUM = ("STRAWBERRY", "MELON", "MILK", "WOOL")',
            '_PREMIUM = (\n'
            '    "STRAWBERRY", "MELON", "MILK", "WOOL", "WHEAT",\n'
            '    "FERTILIZER", "EGG", "TOMATO", "CARROT",\n'
            ')',
        )
    agent_marker = "\ndef agent(obs):"
    if alternate_actions is not None:
        portfolio_engine = r'''
_PORTFOLIO_MODE = {0: "primary", 1: "primary"}


def _activate_action_book(obs, step):
    """Select a compatible opening after observing the opponent's first turn."""
    global _ACTIONS
    seat = 1 if int(_get(obs, "player", 0) or 0) == 1 else 0
    if step == 0:
        _PORTFOLIO_MODE[seat] = "primary"
    elif step == 1:
        farms = list(_get(obs, "farms", []) or [])
        opponent = farms[1 - seat] if len(farms) >= 2 else {}
        opponent_money = float(_get(opponent, "money", 10**9) or 0)
        # The alternate industrial route uniquely spends down to about $25 on
        # turn zero.  The narrow interval avoids misclassifying other openings.
        _PORTFOLIO_MODE[seat] = (
            "alternate" if 18.0 <= opponent_money <= 32.0 else "primary"
        )
    mode = _PORTFOLIO_MODE[seat]
    _ACTIONS = _ALTERNATE_ACTIONS if mode == "alternate" else _PRIMARY_ACTIONS
    return mode
'''
        readable_logic = readable_logic.replace(
            agent_marker,
            "\n" + portfolio_engine.strip() + "\n\n\ndef agent(obs):",
            1,
        )
        readable_logic = readable_logic.replace(
            "        step = _step(obs)\n"
            "        action = _weed_repair_action(obs, _copy_action(_ACTIONS[step]), step)",
            "        step = _step(obs)\n"
            "        mode = _activate_action_book(obs, step)\n"
            "        action = _copy_action(_ACTIONS[step])\n"
            "        if mode == \"alternate\" and step == 1:\n"
            "            # Bridge the primary turn-zero purchase into the alternate route.\n"
            "            action[\"market\"] = [[\"BUY_PRODUCT\", \"WHEAT\", 5]]\n"
            "        action = _weed_repair_action(obs, action, step)",
            1,
        )
    if threat_markets is not None:
        threat_engine = r'''
def _counter_order(action, step):
    """Prioritize products a recognized threat is selling on this turn."""
    # The threat tape describes the primary opening.  Keep an independently
    # selected alternate route's tested order intact.
    if "_PRIMARY_ACTIONS" in globals() and _ACTIONS is not _PRIMARY_ACTIONS:
        return action
    if not (0 <= step < len(_THREAT_MARKETS)):
        return action
    threat_items = [
        order[1] for order in (_THREAT_MARKETS[step] or [])
        if len(order) >= 3 and order[0] == "SELL"
    ]
    if not threat_items:
        return action
    ranks = {item: index for index, item in enumerate(threat_items)}
    market = list(action.get("market") or [])
    sells = [(index, list(order)) for index, order in enumerate(market)
             if len(order) >= 3 and order[0] == "SELL"]
    if len(sells) < 2:
        return action
    reordered = sorted(
        sells,
        key=lambda row: (ranks.get(row[1][1], len(ranks)), row[0]),
    )
    iterator = iter(order for _index, order in reordered)
    action["market"] = [
        next(iterator) if len(order) >= 3 and order[0] == "SELL" else order
        for order in market
    ]
    return action
'''
        readable_logic = readable_logic.replace(
            agent_marker,
            "\n" + threat_engine.strip() + "\n\n\ndef agent(obs):",
            1,
        )
        readable_logic = readable_logic.replace(
            "        action = _repay_shift(obs, action, step)",
            "        action = _counter_order(action, step)\n"
            "        action = _repay_shift(obs, action, step)",
            1,
        )
    readable_logic = readable_logic.replace(
        agent_marker,
        "\n" + COMPLETE_ACTION_ENGINE.strip() + "\n\n\ndef agent(obs):",
        1,
    )
    readable_logic = readable_logic.replace(
        "    except Exception:\n        _seat, farm = _farm(obs)\n        return {\n"
        "            \"farmer\": [\"PASS\"],\n"
        "            \"hands\": [[\"PASS\"] for _ in (_get(farm, \"hands\", []) or [])],\n"
        "            \"market\": [],\n        }",
        "    except Exception:\n        try:\n            return _recovery_agent(obs)\n"
        "        except Exception:\n            _seat, farm = _farm(obs)\n            return {\n"
        "                \"farmer\": [\"PASS\"],\n"
        "                \"hands\": [[\"PASS\"] for _ in (_get(farm, \"hands\", []) or [])],\n"
        "                \"market\": [],\n            }",
        1,
    )

    version = "V17" if alternate_actions is not None else "V16" if all_product_preempt else "V15"
    header = f'''"""Transparent {version} Kaggriculture agent.

Architecture
------------
1. A tested 719-turn production/opening book provides long-horizon planning.
2. Every book action passes through public-state legality and shed checks.
3. Weed recovery repairs stochastic blocked BUILD/PLANT actions and catches up.
4. Market counterplay can shift a bounded future premium sale one turn early.
5. The final turn liquidates every sellable item that remains in the shed.

The strategy data below is deliberately plain Python.  It is not encrypted,
compressed, encoded, or dynamically evaluated.
"""

from __future__ import annotations

import copy

'''
    actions_literal = pprint.pformat(actions, width=120, compact=True, sort_dicts=False)
    hazards = pprint.pformat(hazard_model, width=120, compact=True, sort_dicts=True)
    action_tables = (
        f"_ACTIONS = {actions_literal}\n\n"
        if alternate_actions is None
        else (
            f"_PRIMARY_ACTIONS = {actions_literal}\n\n"
            f"_ALTERNATE_ACTIONS = {pprint.pformat(alternate_actions, width=120, compact=True, sort_dicts=False)}\n\n"
            "_ACTIONS = _PRIMARY_ACTIONS\n\n"
        )
    )
    route_hash_lines = f"_ROUTE_ACTION_SHA256 = {route_hash!r}\n"
    if alternate_hash is not None:
        route_hash_lines += f"_ALTERNATE_ACTION_SHA256 = {alternate_hash!r}\n"
    threat_table = (
        ""
        if threat_markets is None
        else "\n# Public opponent market schedule used only to prioritize contested sells.\n"
        + f"_THREAT_MARKETS = {pprint.pformat(threat_markets, width=120, compact=True, sort_dicts=False)}\n"
    )
    generated = (
        header
        + "# Complete legal action book: one entry for each decision turn.\n"
        + action_tables
        + route_hash_lines
        + threat_table
        + f"_ARCHITECTURE = '{version} transparent route, recovery, and all-product market search'\n\n"
        + "# Empirical premium-sale hazard model. Keys are upcoming turn numbers.\n"
        + f"_GOLD_HAZARD = {hazards}\n\n"
        + readable_logic
    )
    destination.write_text(generated, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=ROOT / "v14_route_x_r3.py")
    parser.add_argument("--unit-source", type=Path)
    parser.add_argument(
        "--all-product-preempt",
        action="store_true",
        help="Counter predicted same-route sales for every product through the endgame",
    )
    parser.add_argument(
        "--threat-source",
        type=Path,
        help="Public route whose same-turn sales should receive counter-order priority",
    )
    parser.add_argument(
        "--hazard-source",
        type=Path,
        help="Public route whose next-turn sales should trigger bounded preemption",
    )
    parser.add_argument(
        "--alternate-source",
        type=Path,
        help="Optional second route selected from the opponent's public turn-one state",
    )
    parser.add_argument("--output", type=Path, default=ROOT / "main_readable.py")
    args = parser.parse_args()
    build(
        args.source.resolve(),
        args.output.resolve(),
        args.unit_source.resolve() if args.unit_source else None,
        args.all_product_preempt,
        args.alternate_source.resolve() if args.alternate_source else None,
        args.threat_source.resolve() if args.threat_source else None,
        args.hazard_source.resolve() if args.hazard_source else None,
    )
    print(args.output.resolve())


if __name__ == "__main__":
    main()
