"""Build a transparent Kaggriculture submission from a tested route module.

The output intentionally stores strategy tables as normal Python literals.
There is no compression, encoding, dynamic evaluation, or generated bytecode in
the submission.  Keeping this builder separate makes route experiments
repeatable while leaving ``main.py`` directly inspectable by humans.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import importlib.util
import json
import pprint
from pathlib import Path


ROOT = Path(__file__).resolve().parent


COMPLETE_ACTION_ENGINE = r'''
# The complete command vocabulary is kept explicit.  The opening book is the
# principal variation; this generator is the recovery/search frontier whenever
# a stochastic board event makes the principal variation unusable.
_DIRECTIONS = ("NORTH", "SOUTH", "EAST", "WEST")
_CROPS = ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON")
_ANIMALS = ("GOOSE", "COW", "SHEEP")
_PRODUCTS = ("WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON",
             "EGG", "MILK", "WOOL", "FERTILIZER")


def _legal_unit_actions(obs, actor_index):
    """Generate every contextually legal command for one worker.

    Movement is always accepted by the simulator (an edge move is a no-op), so
    all four directions remain in the legal frontier.  Resource actions are
    emitted only when the public/private state shows they can have an effect.
    """
    _seat, farm = _farm(obs)
    private = _get(obs, "private", {}) or {}
    positions = [_get(farm, "farmer", [0, 0]), *list(_get(farm, "hands", []) or [])]
    inventories = list(_get(private, "inventories", []) or [])
    if actor_index >= len(positions):
        return [["PASS"]]
    position = positions[actor_index]
    inventory = dict(inventories[actor_index] or {}) if actor_index < len(inventories) else {}
    seeds = dict(_get(private, "seeds", {}) or {})
    shed = dict(_get(private, "shed", {}) or {})
    tile = _tile_at(farm, position)
    actions = [["PASS"], *[[direction] for direction in _DIRECTIONS]]

    if tile is None:
        actions.extend([["BUILD_COOP"], ["BUILD_PASTURE"]])
        actions.extend([["PLANT", crop] for crop in _CROPS if int(seeds.get(crop, 0) or 0) > 0])
    elif isinstance(tile, dict):
        kind = str(tile.get("kind", "")).upper()
        animal = str(tile.get("animal", "")).upper()
        if kind == "WEED":
            actions.append(["DIG"])
        elif kind == "PLANT":
            actions.append(["DIG"])
            if not tile.get("watered_today", False):
                actions.append(["WATER"])
            if int(inventory.get("FERTILIZER", 0) or 0) > 0:
                actions.append(["FERTILIZE"])
            if int(tile.get("yield_units", 0) or 0) > 0:
                actions.append(["HARVEST"])
        elif kind in ("COOP", "PASTURE"):
            if animal:
                if not tile.get("cared_today", False):
                    actions.append(["CARE"])
                if not tile.get("fed_today", False) and int(inventory.get("WHEAT", 0) or 0) > 0:
                    actions.append(["FEED"])
                if int(tile.get("yield_units", 0) or 0) > 0:
                    actions.append(["HARVEST"])
                if tile.get("fertilizer_available", False):
                    actions.append(["COLLECT_FERTILIZER"])
            else:
                actions.append(["DIG"])
                compatible = ("GOOSE",) if kind == "COOP" else ("COW", "SHEEP")
                actions.extend([["PLACE", item, 1] for item in compatible
                                if int(inventory.get(item, 0) or 0) > 0])

    tiles = list(_get(farm, "tiles", []) or [])
    try:
        adjacent = (int(position[0]), int(position[1])) in _shed_access(len(tiles) or 10)
    except (TypeError, ValueError, IndexError):
        adjacent = False
    if adjacent:
        if any(int(value or 0) > 0 for value in inventory.values()):
            actions.append(["DROP"])
        actions.extend([["PICKUP", item, int(quantity)] for item, quantity in shed.items()
                        if int(quantity or 0) > 0])
        actions.extend([["PLACE", item, int(quantity)] for item, quantity in inventory.items()
                        if int(quantity or 0) > 0])
    return actions


def _legal_market_orders(obs):
    """Generate the complete one-order market frontier for search/recovery."""
    _seat, farm = _farm(obs)
    private = _get(obs, "private", {}) or {}
    shed = dict(_get(private, "shed", {}) or {})
    orders = []
    orders.extend([["BUY_SEED", crop, 1] for crop in _CROPS])
    orders.extend([["BUY_ANIMAL", animal, 1] for animal in _ANIMALS])
    orders.extend([["BUY_PRODUCT", item, 1] for item in ("WHEAT", "FERTILIZER")])
    orders.extend([["SELL", item, int(shed.get(item, 0) or 0)] for item in _PRODUCTS
                   if int(shed.get(item, 0) or 0) > 0])
    orders.append(["HIRE"])
    if len(_get(farm, "unlocked_quadrants", []) or []) < 4:
        orders.append(["BUY_LAND"])
    return orders


def _recovery_agent(obs):
    """Choose survival-first moves if the principal evaluator ever raises."""
    _seat, farm = _farm(obs)
    unit_count = 1 + len(_get(farm, "hands", []) or [])
    priorities = {
        "FEED": 100, "WATER": 95, "HARVEST": 85,
        "COLLECT_FERTILIZER": 75, "CARE": 65, "DIG": 45,
        "DROP": 35, "PASS": 0,
    }
    chosen = []
    for actor_index in range(unit_count):
        legal = _legal_unit_actions(obs, actor_index)
        chosen.append(max(legal, key=lambda row: priorities.get(row[0], 5)))
    action = {"farmer": chosen[0], "hands": chosen[1:], "market": []}
    if _step(obs) == len(_ACTIONS) - 1:
        action = _terminal_market(obs, action)
    return action
'''


def load_module(path: Path):
    spec = importlib.util.spec_from_file_location("readable_route_source", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import route source: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _read_route(path: Path) -> dict:
    with gzip.open(path, "rt", encoding="utf-8") as handle:
        return json.load(handle)


def build(source: Path, destination: Path, unit_source: Path | None = None) -> None:
    if source.name.endswith(".json.gz"):
        payload = _read_route(source)
        actions = payload["actions"]
        if unit_source is not None:
            unit_actions = _read_route(unit_source)["actions"]
            if len(unit_actions) != len(actions):
                raise RuntimeError("Market and worker routes have different lengths")
            actions = [
                {
                    "farmer": row_units.get("farmer", ["PASS"]),
                    "hands": row_units.get("hands", []),
                    "market": row_market.get("market", []),
                }
                for row_market, row_units in zip(actions, unit_actions)
            ]
        canonical = json.dumps(actions, separators=(",", ":"), sort_keys=True).encode("utf-8")
        route_hash = hashlib.sha256(canonical).hexdigest()
        # Route files contain data only.  Reuse the tested readable recovery and
        # market implementation, but never its encoded action data.
        logic_source = ROOT / "v14_route_x_r3.py"
        module = load_module(logic_source)
        source_text = logic_source.read_text(encoding="utf-8")
    else:
        module = load_module(source)
        actions = module._ACTIONS
        route_hash = module._ROUTE_ACTION_SHA256
        source_text = source.read_text(encoding="utf-8")
    marker = "_WEED_REPLAY_STEPS ="
    marker_at = source_text.index(marker)
    readable_logic = source_text[marker_at:]
    agent_marker = "\ndef agent(obs):"
    readable_logic = readable_logic.replace(
        agent_marker,
        "\n" + COMPLETE_ACTION_ENGINE.strip() + "\n\n\ndef agent(obs):",
        1,
    )
    readable_logic = readable_logic.replace(
        "    except Exception:\n        _seat, farm = _farm(obs)\n        return {\n"
        "            \"farmer\": [\"PASS\"],\n"
        "            \"hands\": [[\"PASS\"] for _ in (_get(farm, \"hands\", []) or [])],\n"
        "            \"market\": [],\n        }",
        "    except Exception:\n        try:\n            return _recovery_agent(obs)\n"
        "        except Exception:\n            _seat, farm = _farm(obs)\n            return {\n"
        "                \"farmer\": [\"PASS\"],\n"
        "                \"hands\": [[\"PASS\"] for _ in (_get(farm, \"hands\", []) or [])],\n"
        "                \"market\": [],\n            }",
        1,
    )

    header = '''"""Transparent V15 Kaggriculture agent.

Architecture
------------
1. A tested 719-turn production/opening book provides long-horizon planning.
2. Every book action passes through public-state legality and shed checks.
3. Weed recovery repairs stochastic blocked BUILD/PLANT actions and catches up.
4. Market counterplay can shift a bounded future premium sale one turn early.
5. The final turn liquidates every sellable item that remains in the shed.

The strategy data below is deliberately plain Python.  It is not encrypted,
compressed, encoded, or dynamically evaluated.
"""

from __future__ import annotations

import copy

'''
    actions_literal = pprint.pformat(actions, width=120, compact=True, sort_dicts=False)
    hazards = pprint.pformat(module._GOLD_HAZARD, width=120, compact=True, sort_dicts=True)
    generated = (
        header
        + "# Complete legal action book: one entry for each decision turn.\n"
        + f"_ACTIONS = {actions_literal}\n\n"
        + f"_ROUTE_ACTION_SHA256 = {route_hash!r}\n"
        + "_ARCHITECTURE = 'V15 transparent route, recovery, and market search'\n\n"
        + "# Empirical premium-sale hazard model. Keys are upcoming turn numbers.\n"
        + f"_GOLD_HAZARD = {hazards}\n\n"
        + readable_logic
    )
    destination.write_text(generated, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=ROOT / "v14_route_x_r3.py")
    parser.add_argument("--unit-source", type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "main_readable.py")
    args = parser.parse_args()
    build(
        args.source.resolve(),
        args.output.resolve(),
        args.unit_source.resolve() if args.unit_source else None,
    )
    print(args.output.resolve())


if __name__ == "__main__":
    main()
