import pandas as pd
import matplotlib.pyplot as plt

comparison = pd.DataFrame([
    ["old v22 artifact", 5, 46],
    ["current v25 artifact", 37, 46],
    ["v26 development inner", 40, 46],
    ["v26 development outer", 40, 43],
    ["v26 strict future", 24, 25],
], columns=["policy / split", "wins", "games"])
comparison["win rate"] = comparison.wins / comparison.games
display(comparison)
ax = comparison.plot.barh(
    x="policy / split", y="win rate", legend=False,
    figsize=(9, 3.8),
    color=["#94a3b8", "#f59e0b", "#0ea5e9", "#14b8a6", "#22c55e"],
)
ax.axvline(0.5, color="#64748b", linestyle="--", linewidth=1)
ax.set(xlabel="Counterfactual win rate", ylabel="", xlim=(0, 1))
ax.grid(axis="x", alpha=0.25)
plt.tight_layout()

import base64
import hashlib
import importlib.util
from pathlib import Path
import tarfile
import zlib

WORK = Path("/kaggle/working")
if not WORK.exists():
    WORK = Path.cwd()
MAIN_PATH = WORK / "main.py"
ARCHIVE_PATH = WORK / "submission.tar.gz"

_AGENT_B85_PARTS = [
    'c-pMH+qR<05-s{ZzoJ|qTeOYUR1~zSAYKsVA}S#IfN~WS6}gB4`t94fS2@lPoO&3|(j+?>nHkZ0WaNMT^PhVi{S#VR^rIzOVEr-T',
    'Ah0gc&)JH!KmIj{?5pQq|Jc{y52GCpfosHG6bIIS|M_RE8O|T;a&Rx!|LfsTU>TNsx57Wy&o}PHw0!IH=Ms6(KX=V@O)av_KgRX!',
    'dsbxq!D{Uv&4}FV<sV%$PWtDe|Ni;2yvEU|hksw?V%@FaPw0ED@p<m-nm-',
    '5aZ2i$L=AWzYf0|#SKkmQ%yV3KH8~%weacG(U{bw0}zWOw@EzA73=YN0m+_U>HdUXBs!Mp}P-',
    'qp~&KkM;$^m%PxbA$i&8<<w$UJie(hZ{zp5C5#jEc++)u2J|$fBw1JwrjYb2mOyBK4U!lpWgoXUi|s>8h-',
    '|Behv6Xye5}Frgi>w``>^5^Pm6x^J)As=O0}QEwu6dpK<k{-',
    '_OVJV~W3@&syYsKc}9n|MSm3yVaN!t2=TiPUrmUPw)S=|F3t|%&_!tlmD95zqSpmFf9EK<iC2W`R|veRr=@8=imSS{vYEfICYC_=',
    'Umn@76>-l9gsI!AF`HBjtND6?2Hch!Rk+nz&4=n2jp&SrO^d7OSP!gjFyR6mz<#*Zm#JM^{A2);|2uhj>2fW_-',
    '58XX0fLK&;OwIQ_lbxB)o7&Z#b;=%U-0H*QVdfq6eVo9NC-',
    'Y+*|v3Knwo}KF(DO|EZ)gN$R7dJWc6})Dh*ErSyLOb{LtUSm3WK`i^I0*xPE;g6U@E<&acglNPkC^m_TX?dd$*3?Hq5Y^{WJ-',
    'ba^Mf13^Z6%*_tL#QKIY_HsE57HAuq`QY&zguUiRbX8Bl<3zUl0nI+PbWdP|Ll#?!qNh-',
    'tJ3}Udq2Aqod@`ZG4p2dS`O^udn2;lF`sV@TdQ-b^1{^mPWd^Snf^+5^(aS-Hl|i*Aimef6astMv;1j2`q6c$fcC8#2)k!&TTfd3',
    'enzZkD%gKe&g4O+@4rx9O+F~L|3#kl`!u_$@XG+%t(`=T{lOGVjuZQA)a~0&;P<zEy-*QuU4VLC`gl2Q06qXPh5EuqO8(-',
    '!hPInQZ@YgRS=TOf+jb#ajwrhZG3%A=soN$~{tHE!(m)N-',
    'L1Xyid2n;qJ%xkQsW6JZ?*gR<zOh@fj(G0S1tjkxdHdB38%Di4Zyqej457&lA_-%b??w7LQKTwyF0$7?8F?eeua(KH-8KhQ9X-',
    'd^uD^-7>RLA=;`If%6st)%y|cyoLGHNwMcAQAJjT6&ahG+eWrUW5DSkM|=YHq=NK#+2_Z&O(O#n%6U<MR!%|)Bu-',
    '5JI1t>bc4p*=Yp&B;+=v@-',
    '<hOe5B8bTI~V6_*;fvYpT1`qL<f1FXK~N=syC0An6{SBq9~u%E`O^H%>tRo0mb$P8Ys*7~j?DL7~^H$b+kBf*GbZ;N%h8_4*gb&L',
    '@mX#W71+)t6x1783QtH)OaFzDps?is!CSvEuMYxX<I7jEf|3uSUJ8zwhDh_QzwqP^bmpcyn|dl)a>u4a{bN7>SI?2j>`Mw_oQ$MZ',
    'a2TJ4!1Tben8n1(I*z0QF3#kMSiaS&>Y6zx7z=@BEHzfgHP>-',
    '2i!TvykZ`vgK3D09mTJ5j;AA&I=J{;_h?_8H%y+Wp45xysa4h%WNVf;nAXn+OL-gb#1zNNGYXT+HS^n01j3x_u`z(7wIGLYb=kg*',
    'v?X6|L-isI0%VLo)LcF#XYMSbZ8&<7r7NTKggZ>)SOJ6AZQf8sqh7?~969&-SaN(-',
    '{iZ&Dpk!PHC{GPGfwsimQ6kaxcvC0N3eOcRQ!^!?e1Bo@sG+4$gzT_Q0?SSVh>up*0nV20be*LS!2%V3ak^`{wVau7~Mh*~-',
    'B3aj;z=`T7Rc$(x25{r26QNy=(GN0$9Fv#aRtDQ54}a7H4O=WE*lQb?~PwXf^q4Ub2Z4Cv)P1wwQi4mEZ*14|BRNF72W{zBC|$R^',
    'n=C6SyThqEw_54IW^s|0LfhSP{ttKJ;Q&Zu-wpPxNaXL~dtCU2oyo3#+T%4x{cf3$#3gG6Q>uCu`Mbpc3n&rD{*nxx?_$=9oYp?1',
    'CMSt>YP=-',
    'C`R<tysb=ukRTC#6RE05b18cyeJZR+Z~)b4kl6_cZzj_BaQz>RT`2=5B9A`_!ID4`M4O<&swzW>)p%#><b{+~JoS!#tlFLv(O2nA',
    'x|-z0uPOv#aB<D`#)l&I{}Qba9RG!n;^54v!%;nmi(>BNY$BbxReyt{uF%6-',
    'O!e*0X?#j5gu71{t3L2%)z&SFEg*%X(GMA~#7c6dWom;4f4Go!xw%=}Y?_bdpBzD+b>W&6u{i(`|_PpnO1%0aq^Z8-',
    'hXY#$>C{!SQyH62z*#?AzZrRvOe|?8?TiqiYxI+{zM;Ua|)e$NjdyyH$6HS{*&BRrsemd2jAqyBln&wN$wHnWa_Go%L|mB@?g6FW',
    'T&MquXv++?K5v5UvLP_=3EJoOuIMxyyB0#x03VhZRTjsDG%<V8j*UyJ~@tcK=yXdt(RQwfY!bkNV1+Dg^3$3J%dtJ$;rZvk{3CgU',
    'Kgw;(AfCvz1*q@CT&W9w$TUFO)NppzJ&#hNV+?2%M|vSqGHj#}^1cRQ2kI)M8P2dL>BvkymT6a_vqV=Vj$JJ>DB<Dw=Q1?>pm6rG',
    'A1bj@Fh&@v1FfOY1fWa}k_Qh5hAndvTdvXt9^UklkKsx^O43Q+0lyY?R}fX*CRD%*m()={;c2X-',
    'jXqI$2)QNJ`jxO<!=RKGg~EJC*lMav(PRV}BMic}ezz-',
    'bAlkd@t?q!gq}Y(yUsbuFv9tD>_X3C~U(H;#d|(zIrS*3;U(|R2x?e@+Y3_Kg_iib|CIYrj@&;!B&@|nD3y#oLj-HR1D2>XU<PaX',
    'xHcn35yRpZl&8F&b<45`w3U8<!V-',
    '+%p~n(z%^@iIW){(zVBRT_8E$YRJa7*p#1H#roP_O(JiWyrmbG3<jfYPNZzT>NoRZNwR`rsUVglcb5P!$=;qBgp4EXCO^^6b>i|s',
    'N(PrEUdiCt)Zl<p?ihR4pD*kwo$OSKviFCpgv4t59GR`)8{aXb*VB{>ARY5g5%(AVaach0kc)i*^b#iT2yT=+dDt>#a+}yV9L6Y1',
    '?*1a(|>0j6k2EzP~U@h@TK-sF$j4%3}?Aa$Sregh4%&4R;_i|P?ht!5<x(DIfxYZk6X@l>(g`_bdpAZ#yXOEt~U#`mP_%9R-',
    'Cyk(WNMQx*A6Ir~SZK2`F=Q777l%D&v0_+ZPGCQSQR9L;`xTP^bS6GHp@&f4Y$?@fyng&V*Nf!sIa9emPp5u)NVu0`*>FesUAC1g',
    '_7@5v0T@M3zn-VYD*fUo?g=qAkUXrzuI9t_hJXej@$tvE$A_M+!qV`tdpC(0X831bhVR#>N&`z;64BcGy#>ndb-',
    '`^1dX>3or4XyggFO=t+|BbTg4$sI7pl!YTVOXbSTH=Tdxd-HaD>*ZG~u4p(wdB|3L4r~BDcBm&%D7hyx5xS?}Z4zu!~dO(S)xz0s',
    'ibQ5C)xRx=yxUAh%kU<8!%?c@imohg8yZ@K#)|iB?ZFx`X(bu!WI7UdI&%XCW+JAO)CI-',
    '|~Jt|31=%tB_Tspg1|0#Di(v4UcS$kN|z{h&>m#&4+jFPL9-',
    '#bSI!b^!I)D6fzz8IH#2NWSfx9Av=o7Tbhj8EU93<64?n7ri?k#tPV)LQyWjeR?rQhbs!Dnl{P*`*y$emA+0~$@Vy~#yaq=BJMCn',
    'lT%XUjSN3j0d$CRcR*S1m9}gNdvkC1Y#buL!*v`W&?>Db0N;`CcA-DS#=1t_+`pZ{<Wi-',
    '8Y`DI}?+>=miBgx~wYGLKd5;NJi?UhNnVEYZRK9jh@+1hgRmM$-J-',
    'jt?G;<!K|WWMjev)X8j&1w|iJ@(tqDttdlKhSHgGPrwm`!Ceb{&b?T&887t#^ZS~nXIp?LO51KuM0WGdn$L&H#EV3f)h6U>gs`(J',
    '`t;ybv|2_K01qeB=z6prrR_7(d3MmNG9idCvbjF73o!9G5#hTrGKH0EVJq4&9%w)yp+7AcXa?S%T?;+%-',
    'H)8p%For$3Me{2=5oX4r^$+E5!0h@*Ik99}D|-',
    '7NyE};y?VSU6<}8kam`^uwm^vr9p>Q>#BL>()Aqv@^>{+kw{+NgA89)p~f^XABSdA=~mV8bt%4-',
    'J|R#@IyAZ{T>2<PQVodcq4kHOal6>2TcZiwv?l3pBk1#!y*&>H?p@ZIeomA7A<n5EGRk;gXFEO|Jt8SvV{#5j?nR%XQ$jR=xxg=G',
    'N#(RH&y4YWHWcxWfqIJ`xAU$@!ex8@z)!Y6+!>Exd%k>+;@S`|!eFTrbyknzX+fsQtpshP`El|Ws%dqy2V+d8$f;jiDTD4|tM4Dt',
    'P&->(>3;7~8+B8wHWI=|-bG52dgC&leoa!Q_l1BzB*~+`ZUcj021IzRoRsfZ{fOn4K~(7}TzyD5wH`ElYTcxKvrpMe-Wsqohlk0u',
    'Szjgl50iS$Ih1`&c-N38?GY`kwN0U1)%xY)S6(5XMFoR$VbyKT;S&%Sup6yMQ+-tly`IhEOO?jj7B(AhCdj<Wru*+Z)@w|Z*P-',
    'o#3fih%;U@(yZjc-',
    'vMEjk(AyKKFq-a(Xg2BbEE>h*`QI@ZoE3zCSaiZRf4nXkU_9FZ!_4HTLc9NpNmhg{+SaCgaVDDjI@2;r)Fu*`Am-huWUhR`{y>Lw',
    'Cr!L9<TydNZs?z;l-',
    '5sVK_S??@3bOmSPn6rJCQ$caV1v!J8qC&7g@=>pLarrFL|42W9h!~ZxhBA(xBZQu<g@hbgzD(P4wBklHV4b5!!6f`J=f~+^lV~5`',
    '=>wXDa4~*?V}W(J$sX!>rRVG_gqtI5T)Xe_d8bBt@Gk~%e^`|;@>xm>x#<eI>h^3BKw9Xd`-',
    'pV!2!P5v3cp|FRgo8S6)HcItV0I!Z=g|maQSQju_p9UURs{RqMklU$OU1`0!kg5V3V!sk`+M3ehV9FcU6uTBbbOd;78()*D&9Ts}',
    'g<Jv?s);x}sW8@VlTK%ahV6`H=E{bH?OJz&d;weFtgro~K`k7cK)QP!_vd_AfQdN&QB=kg|kf=#t0w8b~OLTwX@<#YGwt`5i9A}g',
    'G4{vvp)&r4UIA#o;0MsH;XGCIaQQ6kUU?8$YeT6Ni80?F%2&=)1T8HAvH1;Y|vV(Dd0v{3(Y7K6=9>T=iiXvUX(+lk1UXy=$)*WE',
    'c$E?7Nga-UO;@}=bFXJfq@cNSs{zwP$u)qV(+dC3)EZ_Ve;%SuO217a&bze9TBZ3!`64cAxL{m!77i<_>+EJPsP?b}LkT{~CBg!1',
    'kc7em3Y^wdX&3Ll*kzbbnf#dQhaJx)qvzr()i-',
    'o3u3gwe{M!xwzi8+zC1BObP2W%tGGNxV6(poJCwq#vjB^t|aY%_K^=eOoWqgCleb9$4VrBs;v0*lP*j7vv&-',
    '28uK0upAgAINa4TAJnT)*zeac4cT?pyO5dnm=5SMh<V?A1C^FX6R;yJT1%>10#kH?H3>jBh=D1t8NzHG=c*Zk$03y<_Vv^kVRVsF',
    'Dc?&*Je6)mq!h!Y(Q3AE2i@!zbyAykS}r<=dP1~d2aW4x7A*ckZ4T#&x`BTeOQoafF^@PkqB7>|__3iKO7sqE;4?jRrNC?C?E94T',
    '@>T{M>Rd*z+g(oZ>Xn3hznjqUJ-wjU7UHZe`|{ot4<&f<0wNkH?>%^x5;bBRF22lbD551^ZJD&TE?%+{f5_$Gs(H{G6Mi>Mf5w;B',
    '74ESkq%naTF?m}Mf?4X8J$q^@&m1o-KI9rhP9t;8K+97j#xA#1IG)z?mY<j3-',
    '0mYTneQZe^Xn_G4A$3$ICkV=C;DtVlcdsFfJ39jz0iq5t&yf0$m9DP>t>MdoGu?K-',
    'aGH7JE8z$yDe^=)_P?#%?I(}{1!XMM=H2C>gK_35bff@<4YhNOF51_^oCH1&=D@zl}GHLX{Dap=VIj=b#&)RuHuu%5nr3LwevKe1',
    'Ij!V^OhH3aJp^Y!Nx$w(r0UPX%m4)-',
    'wq&BKfpo)^lxiyDM#I8|16Bs7R?xviL>X|%PFUDMY>&<n{X;Q@2AJ%`n~y4+GuC^l}HC?ahaC)x0XKW?0kwEod<}eJvpS;mZqJDH',
    '`>CAPy5MBncp@qyFJ*M^Nl(iRpR}6bDVeKa6t~n%av8!!;2)psZM*jDW5Ag_u!Gi7_Eu3<=5s5u`2aKIBQkkMVSd7YjKHhDgy|Aj',
    '<nA*Id)H~inL}MG}!R31ZeqscRO#_2Dg!u6q36<Y;|XmzKMMv+63tG+P0KQ;S6eDv-OWH^ibNQJ7u$LS8g5R6u{CUyua(bV3W+Q(',
    '5hF4d9C+qx+SQ`p2z;ZCEXRfd=!FCf;OL@EjRBmyN;RiRS>pT*XKcFQQ<Z*26Pxb@_7UL3spVz+sH}Kx1Eu?<A_>oC~O*OcMOf1$',
    'MSO#Z#(bP16(YhSnmz1ud;Z~i%@rXyD74Mn#j~OWh>>b{~#`~gsU3|A;@vd8^w(9YM4Xl0^cvnU#PV*ACwgPxP*4oe3T^x;bCDg6',
    '0mj{mYS+pzUNiYLQPK+;+X@`_DzRwK;Ur-y%;*aKE8KcIeM^#mEozi1$NtltI2TA;{CZgfL`zPqz-;lAIDZu1hmB*U0d-',
    '_<>N}gb-',
    'v~8`~qF)w6=R~5xd<I;aKcmBm`$KZOTN}nYO5*iqL@lYO{2%m0hbfVY1QlXMGPhQn^s9U0&~XU+|UEf&G%yO7Up+4#Sb>T}MQFyO',
    '$f;>)~UFh$Cx)cS}-e5Bc)GH07J6?ghAViUdUH85lfJ<XUNWevH{t{{j3yzgf$T-1O#FJ2|Zjb>q7n;1`K{d-',
    't&Pw0~XrLfzY(j_t!$H`lN0W7xLxhSYgGXE`pWSEjM#<*_$z+K>3Tm_4T3XT6f5{LGF$wwaU;C|T)mH~2=_*nldgT%-',
    'J^Uf=BYEuQ4<LlbMsYcuNG=UKCO05JK~JY2-',
    '~&3%{b9z?)hJ2Ia+p94)er_t$tnew&>PKvwc1IG%*GQ<xUk+hF8L28?)b;khW_GlhIDlj9_zfkB;9LroY4tK~v_(-',
    'WX5mnm?B^FpNXq<wo<Cs8qufWB_^i<>TUTLjA<I(9fiK|hG!lOdcPAfY6Krd_et<_hk_wt4MD{1{6kq|CCzmgTcq-',
    'r?zjNz<nVd<{OK(mRDk#GPQ+<H>97wI&8v|G^nMe3s4!q+zOJXD}&?h$@*y~!@^?j!m<Rj0Y4@2(@R_rP4RzplWgO!^DOoI0JwxU',
    '8H7(h*{<KARWyZ2LB>LuGL-_(+SbLTJ4mgH3)?D~u|sXy~1}u`t6J>K@a<RMy^ty0EMq74I<L{SIM_o&2f2<iq2-',
    'OMAV^=}O(u^Deyuhkk974(^N-?-',
    'oaHg!dD=fbBvuh~Z;(f<aFTQ|Q&|*%!Jmjy%iyP7^yy+8Q)A)mDHOHX<3ct)NoueJQHW`6{(9m6t6NgyInCZpoyy8Zvr-',
    '>&jN&OcRE9;Sc?Gkne7O73c+etwmmE(>L<v3TvU)3(iRgO(?JjCRHdo=5lyj--whL1j0JW>-',
    't})*1lzf&vdyJ*WC&gZCpK=ES8y}tmqq6h23kQOm<A`x*4b_Fg5y3b-',
    't)~>Dq=mFeghfCh6h*wNPqK(10(pLWpKAQZ}88bv3%My+FAFOQm7at(mJxjq{4)f{0XmC;-',
    '9DWzJfCdsuGvrR?Elwbtr~Wfqr!8^QF=pR}!Z3y;&+YH&&U-DR7`N!K>?y*^4VdBJ=_!dkfZrnWeX%G_-qhG1D?KlGTW3IaIz;rv',
    'Z^?%37QJpK8qFu!?$UfyjF0+AwjG6!I4S#*;t5(6CRki_ik{am?LO6p#X@kZ(17Q6V-',
    '?xEfBwo^cRnolgE&ODhJWzQS=m~;{5eeC%lD$aNjE)G|!>D<35f!MS*Q;Ha?@LHoKc?SMe0_Eq&<+#DC0V~s0(4e-',
    'bv4rbhW19BnRFzUL^$G4ShE2J(I2YdL(O59ZrP4~AoMw|o{n;3b<<hXAqvd*|VV%B<Kc&ly%)3cd!Qdw3O4)U;08p_GrI4g$9(>D',
    '%b8cpreskE-c=80TZ}W)Yu;!M?x#u%3^UKn9>`c^$*_pq_zxx-Ch}(XtLm47gJEwM<xi`M8GpgOMKHj0&9JuE;B9_UqxQ`avR;xr',
    '^lIY)t?%L1x%2Hm%;ImcrpRe=SYS<YR6~^smF&~G1$1G(<y%e+NH<vr5Hl11CsocjwBXM<I8xFTc(ASXJS{pK|c}Mrx%O~uqFj0N',
    'T{&X|Ku+?@Rx_;jm3t+o-h)J48YlA~N#JvcBs`p7a6OPewGSs-',
    'o;yOBfMgP9^1Du>6sMI&l+#wRrnqD6_Z^iJi?Spq@)~1!q3w<2>LHV|66_rgf9=~Hh?;2e7?Ty^z?zfs7FS>hY{`XL@a-',
    'rFoXb>fQ6hw89tDDTVFYb{A<j*H@tN2r@(0ra3Ko9#qVr;vG;o(A6X*oe#$o;A|_Lsq<`QayRl2@Yapg+yDJ@v5qao{42skyn2<5',
    'i5zX*Ky6YFaEb8LjWqyPw0!-FUk-uE;%U*}N(d{6MVRE%=6&+xjR1jmvy=oJkMaI>_i;1w>={I50UqSB0@5N!{PHUW?WIvs|q2yI',
    'Uyc7SwL3-#1Hmm`*Id^c04^3UK}v9rpm#G8MFJF95$dFt^uIcg4MGzn-BR7cpjR+)W-',
    'XiXvQj4pM;ix0U?7(~fCLt`*a%+4H;mKG-|l1%F4&Kk?6HGvtz|>iF+{S_O3@bPC$24tiJl&5zpKRNAzD`K^<#&uHa_c4yD-',
    'Yb7@>)gku2FDv^^aKqyQGbq$nsdSD%lxTOgdEzJqmX$6KcVl-an;(J%mrv$$G0=Lz`#Rp8fl)6S4cz&2IseVuW<DzKJJWLMndN17',
    'mq5GXmQg*jkdla7UCME*_m+pHRc$<9jS^!xTbcTdm?9`SF4fLA8KXMwP3cr^*z$CT%f)-',
    'YaC)c>xn>fvx($w}<>|}tceNkhr7C0n_}=5OJiYf>NT!`u!!i<0im}CD9~_Tb2ax+EtylSY<#Tt0+|J?=+U6QJI+JuA#JTUAOCx@',
    'nC|#x9p)jI+S@qBss#R@gpNK&-e9QyUnq+=;b0pf`d{?rG2QrO8udWP=C#U^<fNg<^-',
    'uT&cIn^CZX3y!cCR`s9Z512L<52MzoctGRa`b+VHG$kL<H@~5&IX0`ZHgs!qdl2rmNX?wev&TPvy>Icot<cB9BF}@XWr*``)ieMf',
    ')bkQcfX=y#aeizJfcts9!sX)EQ|KfIl#{Y<D0ab(Tt)ER*Fdp+umu9s8UudPuJMS>Xia(cj6rFx-',
    '~^0>BK539Pq5hEUY@kcc$l{4g#~5EhpO|a7HG<`I@(b(@9)Fm$cCYSz|A8p^mMLUv6m|tH_<M>bUc$;@Y6Ny2WKylCKeMB0tTW-',
    'gj_jIz60LzBV!@MsnX+lZkV1v}XH!?+j!^nBqm}_??jkf=2h%sj?FdYSQBTtYcL-JXt<M3-',
    'sb{F4Vxu6FRQko*n5a<eO19r+Y)|#qN|vncJp|F<9TlwWb*Loy7{iHI8@AI7jR*yk+I(oo^_8?pt!O9=u=pCaxtiSg7|&YAtRkIc',
    'Nb;4ABrcqUKGuByGXP3fb(yQ>j6a^qBt)CKK=PN5tO4Y!T+gM`ul56Bh@KG#&q>LMIL&beK1c89RXgLXGy*%86+!PXU^2D#?Al?f',
    '@qW8Syl^R!>k=pXbe{Flv%K_tV`hL$+Q-',
    'j;m?A@fbza8PObX8WBU$thXNXMuzD7fml+nouhB^S#y#f*T1I+G^01yFzk57^ZsMcTHtg~()<eUe`4&y5Q?MYZg_=`fH*G-',
    't+VT{okLkXW#VID#T?-s2xhibHT&g{U4_XA66;otc7JndKW4{$*n*6g9({#bHRav-',
    '32(QOb^)zJb8PfGus*JIXD1@gsmJzZYmfQcdrv*JNc33g{ezJG0fNj}(6&eQj8=Y-',
    ';qX36h4tys1v!8BtnX@LkVyjS9Q=I8G>4~W^T-',
    'RAIvRG29^4bQH+3j>kY+gfNp6LUId}Soi8S+T=ShKMwTP<x7HEKJ;uU_+wbc%sUBH&%<h#peu<RqF@!WTXp`bh`fLhsDpfZ|`NAr',
    ')cc#xI01;>L8r*oYtD_s^Ub)5Q>W%F))h|F*~ovBgDMrYr?*URUw9A7NjfiKZB>l|<JRI7DaCIH)Snu&Yt2s#0q-IH=T{{-',
    '1miKF?_@b-gX0qQUnj8}K2S75-^&t(6DOmFkaC5YXobTxFiGW_*dWobK>dUF)a@SU6wj|n#o!4c#1yZSF7Z!MB-',
    '3Yt#(xSL2(#_Os}oPDXU9n38_50BN+kYD8a1v$c|-',
    'k)<XzB{<Pmp;L{MQgojC`B#y&g@89X{BbeY4FG|52Zl%vwe0WQJ)<BV3SZ{<kUJFNS&%^!gyzTd^$p`X~QAGrIZ^uRPmPbPQBj%^',
    'Vg9}^fI{AZ)V@n#9~=1)u>e1j|W#EfL_jGX9@<(7QUOaQ+kq5>m+sUSi_{3DUO2QL$yx~5$s;4fmP9+c5esA7#!|D$}yTKo?ndCO',
    'N&$hG=5359{)l##MCNgjsu0;@s?iiQ=15I9Pe>{e|ayUZN=2VHj>4YZs)-',
    '1yXXA>%W`;w1{qykK0>lfaLHchBOaF>qH>xykU%D&J5Kwf;Nk%G^ijH->$_X6?hvj-KAhF5P{vLLB3`|AC9l66UH2?h&#Ax{`mH9',
    'uG@mIdm*H=6$lpDn#iWk)H7q&DjZz6b-4GuOb&r|fmB1(kZ&Zis`<Y{KW;;A#tgy4d!lENXr0r-+R-',
    'P&?TB4<E^wCb2=cRHsFteY}<z9SmTxGP_&A(aITQICWH$5hObA#I9iC>Zx+UEw%X2MR#IdCbo${T`<Uq`16VH$OoJA%Ify!UD4R<',
    'u$;5qr7RUY-',
    'c#{t`r?Om<7Vk22$?9jaN13`Jh7zkctQWMiwW<zZPg$bm&JaLP$*qU#PAVIC>G9#?A9fSD?KxqCH}8oQ6qPDsI>lYK~^)?;c+UVC',
    'Ev;8${SwYsj}17lv27n@)dLf=Vx;B)8Q#l>wn%=H3YfVy}t$-',
    'OsFdJP)iM(3(}!t0}5N_|x7fa?=sT^QFopOqkQ<kA)(jav=BMXNS<`Vb%OcsFaClYH5R+1d_@gZYu~r+Z2mx&?P}Jm@#)={OYhoD',
    'kRNKs^0W*Yj^3<uiL9{OZbHki@Dxyz;*e=rifn3b}PEH6j@Te#Iq6LKzgqn^4y1(y%gB+V!Oa^ofAI^R@8+m<%TIjbKClLG0V^Gz',
    'quv;3?*7xnptwXdKV08bi@|;dJl!yM<kAT=-@#9y+lM%Z}_!%vk-',
    'Xj6(Zu?(U<e%k-3WuRy}H)LBn1iF`Zik8qP+dZX0qE!FwtC6{>hz{Sl%6Cn#VzuN27`y1E3@6VA~q%$*IE#lEOTz!wj3WY?xT-xi',
    '^kuPVNQ?c&H&HsLa|AFEE{;g^KPaN4lt^dIA|4L(P|38+-',
    'dW$BsG_8kyIg<Q#^z0AWo?2<KFQz9uqbq#MtM$`(LLry^>L<^54jbR%;fQ9(mCywnTmfQdeWd#cchgNW{dF=gHGQ@@GrjcIIo$kl',
    'CXFt6;gnHxN_OE!vr!h;$%$cde=K!wByJJBnCKUEbM!fyU70^@-n%w*Vgce0<<$MbFI!^Ib7d>V^PRs4e`_9?W8p-',
    '=A&VXwDrez$e`dTPOlID3!eHZzvfRD;Y+k$1+Pjtw`S5kV%?7)*`Vq#bx{L1xmCH8!x-',
    'u4)ACihzvTKQ2=xsjAr|EJ_#8>T`2dqx-cA>WR9)fKRXbr2};PZN>U$|2$3rewqf^IJ!b>8Z!neR{5t1)q(yb2)AN8x!wR~6}gzG',
    'EibPnB2J+a23;-1b`QoU0out#;{?g>P=(LdX&fxd*IxgSyX6XIZ}ut_D^<=wa3<KIWw^_rMN!R-mxu-lO))^oTDk-',
    'KI%-youaj@2fe)N>B97J?<xX$5$qfQCOr)Wj${S*~wR)u<Pa1-Fh@8mE~s}1WjmO@Jyw&Jx$wBCE5;2yiq3lvrq5!WS?CIN*GY-v',
    'sSFV*;Y3r+TX-',
    '4P@hoUU?N2=CO`7f!HWDxaOg8P#nn5DPGNbH>Wh<CR^qkDoW;N~@A>Va?sI#R(9=Or*Y*jH&$;+X3PjsTo`V{bykZgIPG{mqSZY3',
    'EzI9~G&qxHRJ)QZlcgKR8Em13tcgbqQUQTqf&;fN8b#U{JH@s>|I+d-',
    'F)ld+ZX@PvLsggClE@?hBRGIFxY)d<#=8bN3v5Reo=&tpvEC(gLpVm$G&{zF%Q5EXEJX$`urATx?;ePIoI`qYTZ;{LObpWuwge?t',
    's8~Bx)5T~#DZ*uRj@m)O6&%>z70ToxOv>V4of7{%y@_zTB-zKm4R2j338)L}!svP*=Q`!B^6ZthkmBi5~kkdL@Hue{;JIXQS(FnG',
    '{VVKt6%i4Ix^5+(iK9Z2GZ3=1imMzPtr4%^Ljc8eY;8YreY7=T6<tE$fA{C1(Y_tk_J@Vgr-VG3PH7;un=ZPjq$C^@%hJ<vHAHdx',
    'R++*{$>!Qt|wtckXI$Ir70?gQHZdb0H0|N$HO!}+G3lWekcO^OLtV8h$%M3r*c9iE!UtBtioMibs(eFYy-',
    'U;mmpLV6ea~(WCV{2YZyJ|XBULMuEy@Q$l9L}%5ypt_h(BQ}k*eQlz#Br1L3BN7#+?a$!@z>NNX*A=hhbr4Pw=JsW*z8y2-',
    'uAjFYNY~mf3)6`-yBI3kLI+|vR)6Pnn{9_2fZ_t)uw{xt#;zTr?WvcX|c*Ler9Ac6>>bwgzauzdN~#O>j<Q?4>-',
    'hdnX&V=(=?6Ab3U8Z?(f!lDCYovx{9D9e>}u_aMdXMV~K4T!?2u<6}tHeD7V>8PT1$3pFH2q^|H+iJhFacZ^?OC&x7!a&yC*<PP5',
    '+Xm7NDzZPxO|3N$MNMqO-',
    '~fWn~79W4#Y<);W#pPeu|o+`DvGUtaw^`_UDiKQK0CM+rWp*S?Bgqcx$34c~@8+ipDE0rq7!CS`?w!ycU6fL+pYF9TeA`EKn_m9S',
    'Uc#TmlfBmx!cB!~HoS)*pw?}`I@5oBl)*7ZFWJ}m}28y+SPR28yIYqDnMCf)MUQ}HaspG^GK0+6GNcX&7*?Rp+Pe4^*=tfXEW#s8',
    'c5|c^`ujF*g`K@PP-A4wM8hxLIrn4Pq57{|kl=jX_WjnuWx7@9SV`MpPuVt|f?5oX+-',
    '#!bgeB8)eqjzANTjM!<mKsnDV{@Ie_xCnMmiPlJXCE#P_AXeh7(k83jZV68ScI_23Ei)Xk7l9nm9|1?fQ#anmgwo~G^=b8c3Cad=',
    '5xMsj~n&AXi?YKWRq}v&Kq;jz`l;jc}}LpU4N<vB+r?nm)BEA&)%zAVW@*tOL*w_{d{z}vC*pm0Rscs%Vr^RXy>~j!O#Q|0FiT9`',
    '7wXCz(>d%EZoqZQ>Wjo0^<@Swy^!^*-{Xyr)tAeZC9=2k4jcho4xCgZvO0=seH^zo`q1>wCt_Pqcr=O-',
    'Z`j*z_tnWz65j0$ZmcK3$um*gW`14FuLty;WwFJbT1=M3TLI3!*q1)ruPQ}u#ujPSa~$otfjwe01zMBXb}T}@%980>s5oyR%iZzH',
    'fDaf+B_cf#jbgH;XVd5Nc=ULEp@RgLLxwi1&j;r?@ZPR_ala74-L|_k(xfW>Qh5j-`1a8xLnh<64QZ25OQxQp*GDcyJff&4-',
    '(>XA_}A|2d%nQb4;y$p30*bQEn+(N6j5HeWG6W0E_<q@;%(`(5uY_h;eZ?)GMq5>+em2u1VO(o(DfU0K|TKsWpqo49d>eTUM5q)9',
    'T@4Sa9WRTcWb1*8S<lY?gK8ErFso>@|&BRAto>Qy8!=azDMRzr{rxTB(8SW39*TR<E{{?FIbil&}$zFKPZ%ZzuyJlZA@eLkW{`mD',
    'lCrhHzAvXF<6(+#<A4Iaxr(2P$W6d!i!|ydpj21}?58k0-iBy##+Vd+Y-}ONu@joO_W_Ekfe+-',
    'EDC6S(R2ER3@)OU@14IL=FtY!vNARr}n+;UL6I^jJw1P?@M%eUPpT{&bla>)p7eNW<ji93P<W*o^{I4UGmM34IPoHUM~$gt2eldQ',
    '#N|@TzcMleRZ2$*OaD%(*m_@zGN-',
    'D9mYNPsjSQ+p42d@_ug^q$TWp8hw0Vp5@S#4U7zM!(yn!dVc+A6)Q&RR&C)k9FcKthK#Sz6C*4b7K`M<3Wrl)`ZN8YNT&xPciNxY',
    'we-3~LWa_Dl-',
    '&+mC{S1cseo);5*^ZsC3^W+rXXxA!rbESb=a@wZ_TVN#{fEvpnFCxdwh*74&bmUNoa>v?ycPE^cOkX!R*~j|K+4VqahDure_%|2s',
    'Fq#7N!2O3w4c>Rr9Q;>Xxbvm#fhH>PEG9`CZk8MgARo1O6dkUSiE;9H43@4-',
    '(~pmX?Md=d;YAcXjYKx5M9>L+8a(820kAqr8K_0PI<F6&xvm_2+~+mR7*b1i}e^>)IXZ9|6BfYRx1_YphmPaClqK$7YQYBkq2k-',
    '&wi!YM1=<+o&bp{$zpI$PiWbZi1G}1q<yW4#S`_RzFx;yp%KhB2+AA|yUOCEpmJC!cH4>}Sb{SD)=FW;=E9_6#H=+~tyxXGiBTEv',
    'R=05{Z{!G5aEc~*I_sMVE!8#xJA{1WXDp<TNNo&lv?0#HCcZ1(Nv>F*beP8K-',
    'Kw^Lc5cNhPIeZ`bH}IObDM0{C%e<&RQ}KjcmHIrGjKi|0ro6@ap%|mDK^Z0ldM_m{78!Z&CD<oYnmp5{d4zT)$ult5|ibR6onFeF',
    'a|)l7){+x0N>2LdMut&^$3!yzfg<$$pDgUZBjC`?Sk^M#fprGH?!oZub0Q?qk1xDZMt}Ip!<XtDBI+~uz(*(sce#X#x8(-',
    'SGI+16<U9!0{IXQX6HJ7gFUkQY|-oF>YCr&pDU>L@6`y9uiJa35~;f@G<{`iHZ>HxMijVHSm<<dXd1D-',
    'PFE6lb)J+=UD_=AZ5|sNn{~Ouxu`I%+rwyjo|bykq~B^w%XjloUV;P6>)_<HG_m%tZ|(vrR9y4avkMC@>m%C6yxZKeS1nudu(a_^',
    'qt&{TZm)&*D%9RjZ$hyfFjncjNLi)p)kh_&S8bO*%XO$!XsHG0XF`VI>Pv{GzJA%B<TR{(cSR*!uL}%&;rODt6XwS{d)Dl3%OR;<',
    'XjJ=2cOzE_XxjaaHV;PcYEIqbq=pn@{iq4|u(?#4Q?(sh<uF*Tdh{049n-',
    'wG2Zsn6t?KPQ*G4624vscO%EQWVyV`t9LqILt2XuDV6K8Ru(C|K}4orvuyT65qZwOo!%`w{>os*h|)-',
    'R>r?*)mMU%ARp`?#48kr<h7@@9u22BCZ`5{sQmv~6Hi#&1hlCF9Q$s)fb#>Q&kFbl&IvO=kpmoYbL+t2M(0ll`zS!7*!XWC-pSz{',
    'FUE+F4e=Su34|u==gC7~QH=R=#53ZF1CCn(H*9m|R?$=1@zTY0Y|J{j&eQGRBW>z(}){#MXF!!Pjc~U`<xOPZu=agvPa?Q&#$_F2',
    'm8xkC`G|-JoBmZHr{FUT<tK`!)bq+U>5$7bJvO7-',
    'RobUHP?x&%(45bQYBR164ZFrt_A8)$T(XG_Ek==B~(A2IbnaRPf5b7c{KNKI|6<YH8P<TLo#l^x@ZK70-+Eko-',
    'N}@^JsDngg@{qGp?lvO7RHS(6ddQb2uw)cEis_Mz6PP|X!|XYUw%KU$rmvI}p#(m6|qX|;~7+@>2JCl(ReWU_pm{exO`kZQ;oyF+',
    'R5y<Vmt(wkE+;?4zJbXd8MU!B7w*>olXw=tr9*s_UtnCDBfP#~|%0rz0&-wH{-',
    'tp)2H@VxOXb(o`c58fctX=yp^G~`m0iZi?yjLyxva2OBac3r58txIBUyG{Ot+o*p6e4$D{%n?VIA*nqa?$zOTbvZr)ZYd1*tyf3H',
    'zt^oy<z0A84Wv*U3wcSSCQ6_V6QDOpsav7BFLkxqpuvxjAU0<uwEx^DW$Q9cgDkE*KiV}e^ir!o)v>p5HvD@tsniSeYKtrkZ>%9#',
    '=BxbjUFTS??38vTIh($6_QYqToV<l~fm`*B`y!7(Q9U=@+dGTxRV%xerSkNCavGhQO7+f%aUBw?kTdu1imC|d7;Vh~oD0Hm*A39X',
    '^6cvDJb8R|`Jq9U@WZUjQ#)*e;w7ibB7H`Q$8<Han^oFUM&6uBB&Z={;k>oTLz9uW>d&443DC{gc45?+M^kwEtZ@3FJv+)jiU1T8',
    'j?}2pW?EIS=C|(iI1O58cYII{YYI0i)!37Q3Hcm>GPqU(M)l+(h>uSNXi&e5a4r5&%~8jNsTX=a-',
    '%3riJBgn+x?1|pQ#)NwZ(gO9mJ$yD9|PBc&ma#X<yd%~O~sDLh0S!QkNZbJ;~whsI&0V!F=j$rc((_9yI@n!eGml|p9LOVF+?U;h',
    '*PfV@WPe|ZF%hf9zdKH-H@o&!z$4{g2z|%m@Tgwzzn+zQ)o^-4B-',
    '%Ld2e3aO5X^VJ|frOtIRrqb$e_FG0U{*h<M+>z3mRWjA_4PY~yvLtvyHk(+S%Rujq+X9&3c-',
    'HN|b}D}^C8#l+@t2_Npsdb}duu%g9ICx1?^nDxALiv;h{&~19APrH)&Wb505dVcrrXuAKF61=k6D9S(TXR${04!zlqIl7Ao3wu#G',
    'li`Hx-0h<jowoaywY#+~#&p05FWzjxe-Fs;RNGvZI=4a9vwEQoRP2Pp#TZ>`kK#ltmtz%T=<m(%Bu$@@5d<j45s$(frxsPHDkT-U',
    'wOnj3liNt?p-|3-h~pgX-',
    'N7D`97pJ~8zt*lJ{>{Zbb=X8tm~enSPH#RAG`ooZ3t?5LINM`*zmviPrxM1hMksmpdAU7*8M>bb*rm3F-',
    'ukor*y){mJtXrnU+;#atijjLMG>fBQkj(Hka!``|S#@P!$G3sbN$yTs92xE?i_V)mv`qUHL?&{9AlAc?}U20!BNc_ac`iY1S(YcB',
    'QNi%}BiBC;@E2t?es}79q1d-3INv!Z)|;&v;0z;1^Xx8;Y}5;d%9(5qylrpX07zZp-',
    '|V)w}ZT=JGrHcR3F)^iH^>8PR6k{z(`F(+2i<FFb^|x3gv)9JxPsxbQJ<R4W&&C$J#RkG>#f1lGhATWdY$ehAd>b$#7guI9JuB&F',
    'AD;(EIGJhlMEWI4ch-',
    '=oE*+m4ztu^Ih_@nVBNt!TE=1th+|rMw8M_|yzO*V4BMJ#o4UmG;<@z+VF}eOBM_`J+QpMB}Bq1E%$%U4~DV;mG0YXid!Rm5iG&%',
    'rB@}{nW09+V6b}WW{XfhIFZrja3`C!7N=)Wi)s+z|GPYN&$1Ez}B-',
    'a(FoP3JQq3>#LC3nbuP}cNFAb?P3^=6fNo0S@pb+w;_Q_@JR46nwq)^QpQhOD_qu;|fE-(`=W-Ey`5Gs$(WUEVhbYuAur}B6-',
    '>bxUI5tj#`u5c(xQ+_`yfwl&FfzI9)arH2T-EBs#}i|E<F^mgYrPKx<x0Cpp+QH7`6#MZ@&2@ZM-',
    '?N7LwC0AA#>YZ$SrZ&iQfA;yMDI6)i%;hebl<<xDnpMtD&cLI&2|YA5iVQiOVtG)9J~eMy!MCvTV#oXunvi_CX65JF?O-',
    'm{q|WfZn|}!Nl3<Yzua~LAg6L?PMbzem@s8GVX7_&NiBQs6SRc!#_83b?4p6@6ML$PPJNTl?~p%85?<iYUM&RN+r2SEO{Cc8Jv>i',
    't=8*EwkvM>d?VDZJ#Ebw4gvWH%N{Wp?AkMKl~p_L)Vm<p$GnQQ{p{73R*iC(U)FBDV+<C|n|T{@*j4@}NGieM>VhoQAxEpv<b8u(',
    'YjJxl7tKLgzS;G8AiT<Dt^e-f*@s1~?-r+ODK;OX@%c47Vt3ZKW98w-',
    'H9rCV+5=j}v$b4Us(_9Xs>zAwrS6TYV0(4C%|9+;axI4R@heJxr~qcg=s5RE+T1T*xqS=hv$GQjGSF`hxl-GnjzLW{4tV!in-zrV',
    'LdsU))2W-',
    'qX1npx^JTCpOw#pzajXj7Vv2Z=&|ie0JUgOV50MRWc`Xv$YFOnu<SLyA{wHWbfjOKtqjwpxU%hW~s%sne*2UO9ISNg4B^S%)le^6',
    'a?qO2nx%cciN8V0zw`RdLd^BMusPy^hI!!(^XkyX-t?fy_Q*~nfe*cPEtp~KdKXCWDqT;^q+EWn~6-',
    '7`MasS)ju!?Q(^3FT2A1X3QCX-~6Oa>Xz$J2~`Fz+?a^jHpN4vWpnu|7wp;gXQ`pi}-bX*!IJWs)0a(V>H1zIa-',
    '5$MsY<pVJ&=on8ksl7(Wroh^vxZf@oFtxGLO(jj}Jha?@BR%z_I*smw<!#d<?7ySueE{g8wfnrDsGi7$>9!2vrejN0)y(KEQ==!M',
    '%k!icUzQRdN7LthZBPNoqOju7dHE0J9j;XieSeQQ&^F`^UBfFl@<Zkh>f|K1WNunEe)fn$K<0%?hdwjk*+-',
    'Tzver+<CXS%_nSyy>bh_8HUBvgz}&$uvKBva$*ak_*PlhLlSHGfExtkqL9e-F*<+un9PdbGh)yjZ?8nDg#5DI-~-Qb_q$61-',
    'mZ_rX@D5Q?oc?LoJ}dovaDCuiv@(Z^dbQEx-7$m-',
    '^5T#+j)I?&_L?N013+s$Uv7#`Y@j(Z<TBIuNchRu0iI%J2D6J|%xE3xBWj}fmF$zb+WcOT*G^;BV<2*||BW4fb7u-',
    'dHc_iv49=~hUIBlPBftNUkyP`b)5XaRc@Ld9l>tE{PV8SluUa@YZulNVRo-gS}v`wu)AgdXpl!MclC3P^A-B-',
    '~)_&AIYb+1pO#dh~>S8CExbcZ$Y5WTv+5f=N_di~HI%5%8GBV&BX@oxDiSF4{hx!z}4IhP?6#CJ!A%BAZxyJD6qcLsLYPm!2=Ub_',
    'v|hdkdqkRGfhp;pCx~PtV#_C|BV!+!F8lx-',
    '{Fs(W#gY<Qn*<y(nLTXXKpbbHmim<G=^b1dNF;(pAqSL{d(67*EKR9C=7)=#qIOCEG5ggl~<^<!~s_IwCPwqj%1wnrl~fAtWk<)6',
    'vPuK08(C<aA70;^hP?MF(y?TD&6kAXq0-',
    'qB9_S*)%H9!S2GhFN@K<zZxh&^Mt*#%M_bi<KbY>vEfd;+H~61>tE}QiDwsCQfEKNz6p3vtbF$UrN6V!`$RVFccxC`gXGyxcnrRz',
    '+6aw%(H(QWQiY0lQ*fijd1+{m<d&IZBMVVTp?IK)$l+>K^K%mz+dCc9p4*c`uA0YB%;D@UrH80AOWWyWX1~Mgo7f^YPrQtg+*{x(',
    '6yC1APQ8O~)^CR_+^*Q1woJ}9!^82*HBlKs-BHxO+T2!kCRvMYJf!iuh2bDFO7vd_yK%njrSK&qtz32UnHRV!x7=HzdT{g3en#en',
    'c@-WqQ~TJD)mr;A?60l;Fi}go2aJ<i<J^{-79!p9cv7w)u?SN{9HkZATt)Z&!nnU$aglJO0=*Ey>I6BQi{$c#)>j52<x-',
    '#LT@}%DJWgBZ!3;s#gX$m<$fQ>#w39mvQ7FuK8PdDumy7O*wA%~4!l@B;>~~&Y-',
    '|vl3j;$Pk+jyT$OyMk4I1FE!scP`xgTnE?Yu%5?hIq%l{V9=aq#}!Oa2Sd0L%W`@H;JNts3q`=TPf*gJoOXtCT8084cba4jzNLt=',
    '|p%mj33}yv>si)c_Zb)h@;PY{&p5bb`;*a^0_y@xE?RBqnYtEv2gawTV~$q;GRS-',
    '(RN15)H2F$;zO5fDIQ}NZ)3U&3VvxEU&O*@F!piWCWI2w%c?%=95=OeXcleB$GuIG=KCQL3ug}FMsT0+I(?_u%e8?y<oq&aCRe^g',
    'vF)lBZijiRS*Y6B{q@rD+PijUDY=e9%mt16M^_&jmC?vz1cytG_&kBa?PjyF?Yb)c08*fq#b&JA^>EosFzgPySJzz7ovxqe>@1TR',
    'P;W*>v+69=+sS2qJz+|@>Nv!LRn*JC90(?p>0yd1N*J@lyy49@>*@KMd0N;q)3d{0Yr+Av;C7d)RZ?p6JEV1S*b%JbZD6Msya;=5',
    '_T(Ybc7}p=!I2z@iP?$|c?(X4OxH7|VTSjLG0BiwX5n!TcOzSY5kt92dsB8?+p~2SA5{Wr^QBzOfyvAp%R?lJr@OvsOq}C@ozUi1',
    '7)SGLqzr8W^`L)K_kiSLJ+Bl6Hq0T;mMq(`<XT*o`VJ|c=~UXuKuw(3yg`5LX#NzJtPCP_%l^Wx8;)r8x+BoV@q$T3_tNKT4%(yM',
    'DV9B+Zi({%$<Alp$uhO!y8G)c?<+Cg0X{vjRSM*8K1beZFB3`mRJMCy@+6&BXeenDR~OQ2RGxx3Uhlk&c+PGQ@JVLnwqbHBO4zea',
    'KI|Mi-NaxyCtBFWy}5R-{qxpwf7Mi)aMG82whCbc-9HqvqfI>>v-',
    '^`lJCYPf911T|rD1HebY+V0tk;ZB*;K!o^YhfMaFq#XGv#R&QU7W`&!3oaGc%dExo%|@206-',
    'h8jZvXvFZjl^BOobaBXk09G+afVRAP0ac0RTNQ*+J<aYRv(4Om`?aNW4Q<WQg7LVHFWzTMl#cr)t+8ti!+8#POron8D45Cd>=IBH',
    'Ql_|dr2#sRKu2khA*A-',
    '_sMVpX$NwU6rcI=Jkvyh85Hnyv0a(_*u_Ecqi?7;JI>q>@aA#v3`c~hlUJhI`(`B197gKLo{m%L;qxmGPB(aYjull2Pig+r<|)6O',
    'u_SOsO)e8tl&i!E*~kva}ncJC_IXde1ZqIDBGg_^A~;Otp^KC^q{ozbz7f~Tc=Yu?T<rx3NwgoiPt%vbtN@{M6J>BMCbJ`<T3ga?',
    ';KE!_^$U?F<mctcDhJFxlP<h5Lu56fu2#4w3T>E*b;N<Me_<Zq!TFVX9{@M4gyh25v3lW^4b185!MvR*jESBASIPdMT)gF*1cbP{',
    '3vpqz0ut5qW3I80kLhaKwohL^}ODY=6ATBe5uE2$6yM@I={7izItsO@dAWMIv6A@XGhr6TTRFXmbmTsyY7E&IV*W|wI#!<~bF*@d',
    'S8dxrKHL4+L`y<VX1T3*V9s3<ijwsm>o@X`%e#U`WG^{H?!<|~NJwwN-76^RdyJtroww(c>s$J-',
    ')wV?gfa!&{5Pxz1I4A#VO+@7LV@+9ns3Hbf?t#n-E%-3Zt4u8v&2y&Wx5Y^?9agEeV6-',
    'rEY}U^NuWt+r`$R0_xeJQ0ta2*$B4*st3OlBwsB-',
    'g(tL2W!K?OdQ<AL*t0??G}hOwzl`pmN>87^P}nE=;dscBeC;rkecQei?eqebULwIu5~+{r^h+A@Wi>zT9S#lEtB#!sxO&sZ5`;ob',
    'VE^S$!&bHB=<wX47=RbeZfEt9khz<u|M1N7u&$~79{rlzL69RBa8TU=S2^hBeZts7nAC_`<7&EiLSW2I)(Dvd{f4E#N=2!*gP*mF',
    '@QA6beZmNOPCLu75bL|bIv3j5u^|8t2g9APn<#{+_Y~(tlWbJ$pd3P)`rEhZhyCuD^#UXN#NpaIMz#TI;A{FV{m8|nZlxNQVXr=4',
    '%+OjS>bdm1!E-=qcALiAARs?0MEva1Cz(G8HZK){tQJjDd{ComU_#PK-gfy*v~C3JEttku%l@n=AG+=eKRH{E?1c4eC`;Qg#;?F8',
    '2H%ph8-0a_N;F(?j;T$d{|@R;(Fn5rZ-',
    '}xHmu;SKDuqX3lh=JX3Ym5>xpvggo$xk7%hsIAy>E28A!OS%b9X4un7^&JSDd2K7(!7IBWji%(<3o^Vn$HY`UW2B7EZf{dIXBtcN',
    'ezBpq8_<Fm1MLk(?tyGu;vT>VwHW%HO7^Wr){SC$dRL#3CY2ym>eYP#@(6*9?N-40c-',
    '_<YonW0|?v9^Ix`e~_we>y7i_c!a!1`L>mrGbsu_9J7zN)#M@2?H`=*48?M6p5xqTx++TZw2_vti*O&$#d36h67)E0)n&ZA!-',
    'uwYLiVEl^S~$h<^jTXBL<#j($|>eWNFp23(NXjwY^Q8vQzu0Q0q2n*pCk;Zr5%%n~5*Oe2?)+H!0PRuP?T!vAYJDkLpmh8sSY}x~',
    'z9k*f&M@c0L$T<y@yZ#49B_FHIBY7Y91;c-m~O6uEBO%kwIaOxaK)+Dk9nq0KDYkeK}~T=y+whe;~B6l&sfaI;G#&$UjvW-en#pv',
    'vz12`C-+`CC|Wx8R!7l27zWX?Agn%FK3kYpnMWx0qtA)V-',
    'Wi;p?cjlja?7oc1g#ZgVBS7&UGn(cZ$*++a8#RGM2)t=!E9*Q=^4QneLp%jL+k*`1?!s62R^7Iw6qTMc?{m}|QVZ3N3U_!q~udyF',
    '=rEE)6F(!9eVhx1Ueod{#_vKw$1Ic&*)a`*S46O4qbKKJHrbxOjWTw__yxAL|4*x#qN5gCdNi?{7~)vnF^QS--it93h8<)AQoS#2',
    'lyt;GfqBoxfCRR0hx*OD!{k__bJ)vb~_-zMF|PHNaEgT!==1;)b?R-',
    '&+7(Um&49QppJB9M_&Hwd4jfuS==%_0YT58v8&!)#n2UtL6Nw*JA9d2@KEswdoM?A5|3(&+fs3APCP;J1Lid|YH)emAv>`iG12Ac',
    'w35!b{Q{v`12JtK>2i>YKj^8&&;MXU;lTsH>8_3<UPl$RAfEvIE&j6Xo}{WUrrb$MF`lB*w!*Cp3n3(lsg(v_Bb+p#w4;+$4Oot&',
    'j`k^SP5CiGl1!xb+*|u08G+9ih69G#;)DB?i@kdpE@0=rlao+lCoeYR3&%(TQg*xNcEt;J``LCv{J;y+8!rrN(|jnXg(ci~|Xff#',
    ')Qy#kV8FKID5ziAaPx?y{>>d?)2k;+a^9Na05LBI0Q@X|Xr{)a~#)IkkJ+L>nb&dGu{N=93CLG`W;_X*$2buT?79Ly$1K2p^d)UP',
    'xyH+^Oz?%qQ&T!OJNo%lNpyuvG?OiO5XO&VKL^%_5D={>Vpa(2SbEn_g-t#|FJ+IkgzqFD1Ex1-',
    'E&m#NV2W%<AB7<1hA0Lq0HUHzM2QvBQ&>L4HH~>Q};;ue}o4P2_Lhi#HXj&8x9LK9pQ<7ScG8E!S$zr`QwvgUH|&tePRPay^fMJI',
    'GIu{|8aQnkBqV)UhU3Q661Bt0bR$z{$6te?37S|LYTqfWOx#pYrcn*zw}?E5HtcFATR(uRZXqhL^^g&6<knwIKQtE3B1B&_Hb0Dp',
    '<RwAO;W<(WCar&@4srD!9*z8!&KN?IzYs;mzhi!ACuJ0_Y>lK`S-',
    '%PN0I9YgKKucU&*>m1}V6y`$l|oPuP<@p`^8{6$EWLb;@JY8fi(d5}xsH=OorwX(`6VjZOadq&L;vv{*zC>Mr!Q|%V{i-',
    'fIT0g3Am0yw%lFsNFllWtqAB!!i5P3WpDUJbi3`mGm+Lrg_hVbpQIn!5f1o@#cg={(V@YZmlK^YuZ`2Fd_yR*6=-',
    '*2Gl|RXndoqhkN*CXQ9^ELcdqKA8-',
    'C;u_3{G?vvU>IQAnY*lKtcD{iBk)$bitXaXEEq#({92$c$2wTPRI6xqG<ptqjcvu@(gpT}rI$we6ln<k^iPy{60KnjNMKPftKYq-',
    'p`4h3AL}*Vk67~ADrjD;q;3g?CB8WyT1^-gnqvubwK(m5KvQx?cp3zfLZ&&_!N|bo^Np1Y8(6kbRRWNW@q<GLbxFAK5Hz+-',
    'W?_f}Bhem%>l3~aRLqQtS*N(LN-}G{CxAyS}rw^T{7W9UKrW`w`7ZOh@?|3(c%mV5F7jO$MAyrBbaDZ)*li4(-0JbQGDd-',
    'r=H1xnv9It#>IeO-)3CSoTd{!lD^bn6dd3;Y4BT!&MQ44Z<d^Q+V-nvd`@1BRW51l>j3t&!x04|-{Di=D8()aoL(D&IC-',
    '}9X0Hxv&{jG+Zl$50h!w5YtlKi9EV>-',
    'j@BP!)4YvNHi7zN?t(E9f6U)tB#Uw`un2fwYFIQT~8GEJQaXzXs}mp!z3DI{YV6S3_dT`~4wqBIt6`hmYz4*YpUQf%dixd8Aa|rP',
    '2cbV<7lxdO!?vibyngg|JRkxhVkIs|;Hxs`mjwz?ROPl?S!;T_N+KaHAeX5Pf1O7E)Vat>?2j5|W`8ETIZc7r^V&ePE^md}kvn1a',
    ';U_Q{^aunA(ZTr)4~MNx`p%YQM0q-Zn=1dwm*{R_RA=fx*a({_itaZTd+az>0hZy&Gnu>Y7mW%#-',
    'Ybf=s^OEc9T#6OD&=z5fru+P@j23jhAgp#AY-',
    ')r@|)gD!WGW+(!PMiJHP)0Pux%e)i$<9$4b*QcZI9}KW}1k9MnJE+dOr9({_S_jWce~+SnKYqL)K6E8csjc_~71$Ydz<HkIU!U5?',
    'Eu~*}73Zd2e|3=0<yyLgXG~ur^5m2v)I%j6%|$V8k=nj$2Tqs+1<+t{I>`HmW}yvvfRv#r(6BOZUR4e0ATUrE3V&$M$FK;Mq%yHg',
    'xAU1zRefr2e{ez%#%KZlVzxg%Q`Qu(vhi_eC~7rTb>7{((#0iH)Qr$h+%UwY&KqMYKFIFNr2O6FRl(G$AG6FrEjlV^hJd^GNUk{x',
    'LzGHCiX;(br0SQbila$_AqA08?gDANp%!b<$(}6`zjS>+E1d1AXDv%G5WX;=1Z+UWWb)lYN@-LsOuwj%;FHr-',
    '+l=X;DDd5C{)WC^pImo;s<(ahN}4nzmKJrTsPw)GVy~76rc?eyJTkSnr}WXj8^Zbcp^Xhds<!j0*dHtCs;1eyZ`@NqX_49p5Nr{@',
    'a=OexSwnq08#LQf=9D(~p4?#hWune??6~H^t)sT|aA*DJmfJ!)llNrG_ygICNV5`U-',
    'Xs^4u01ewErWW028kY6U3^$MQGr2xeC*fC(!0v+hY>9v2r9Xba_G#n#TQZxAnSRG##Gu-CHA_XzNV`G(&1lyo8p=b|7Kx8p#Dvar',
    'Uj@yzCM}GU3K;9$Y8}3C{_YmB}EE4(OVM;@bI8Ii|%xTxZ8uNb9JKY)}efVdo&CUk!B5}1z%WBv}WlBW3Q?@U=u>W{p-',
    ')Rq35RxBnW9bCRmiDI)!qE028a-0ShTGMS-HKU_ta3a!QO-_4IvgwRZby7z&2I)=-',
    '9^eAQ;~8ps7qU>gvgVl&Tw;Xsp<5eO82s2REG3r!Q%6Jt}cchC5}@x4E13OU0~7zVHFQ)z#|LewDi;J+Ti&u@~P2O8+FhcNg1SYx',
    'EbOL9v=EO2VC+VV`-',
    'mU<0{D`6e^30C)Wh9mX0AZ+GztQtRJ=34*z72g+VVfP!zC)aN=6m@*YQO=k8sWj<)ePxSV{00lOpxZy7p~xQ)5eWT>0Ec8j=Sdo9',
    '>Yj3`A~mI~txE{?ye&wH1B!3hgViC&A9aB%zvzE`qIMF^&=a1P0EhtAx!~S}VmO(YOYGFR2F3}@9QdpWx2N<L?OJOAdV}sE`=K`X',
    'uJrz)7yQi0th1sd=641xo@ldWXi=Ie24Up@s7qn{=|97ctgNcs-)FCO)>uqKa9c>azC*UK0leE?RzJS_W-D_KLio&_Ra$>y?(I9~',
    'tjKqHy;&K3SkNi+##%eo@_t@9UJX)vgJIJ;XaQt<45Ke^AJ(RKHCo)B3I_s>;)+1VA#E9BN~-',
    'c;XKF^EFP1@m;C*OQ?<>AWv2^8NxaV)0(GSI?KbnqiGzQb^sd0ob<#<ZV=dA4OzWUptS(m-4Q+a-)+4-',
    '|>j=((C#Dj+nPT;SLtDQt@2j=MxN|UaJ;Q4^zhvm^fE{TAbQ*UW=RS8J<#k*ctcvUJV)-',
    '{Z22s*R|rv?nY<qM9geBld%cKZvoehwdD?a3@vm^WXaG@qhYWA%c?1Nu(lM8&=}dEZ@wLPhJ@An~26`oaXP^<nWM49IKvPu=_zDc',
    '}kWWx|gY5tWA724<oeiXKPxX6@WGPwmV?Vhb8(<WW=OrxKmQk+GmvjyZhLxN_%<HiRX&eXQ*$U;tWT8E(1;YeE&`YpFyTkzg?M$E',
    'u+MSf}_5saTH3r&0kQX7_}p_NWNN)Ft}*=UQY7Ab+YvYSeY&+J8-K>b4GICbmkyiaSsT_silmxtTN-Ra<_j?5jDL0t|c<{E)w?vl',
    '~z{P#^O$y>mB+UXKF%?{VmgF+dNP%Adz5G8x3JH9PbH+%Pnyz^icoZK?N%m1iZBv~GWx<fdwgm(YvHPinOmAQ`k{4~1Qg70+kn-',
    '>Fnn>%&(?#a~ALzpFn#atwc=1{D4X@+i7HKX=qmMy<`DnQFqHZt6t{v#R>ve}<7GcXAuhDGeg9x*hOI9FNlYji4WZRG~wvRun#!g',
    '1WwV@>uSn`aKl>ZhXHt%ugy*{glbR)t_lJ4ELmlDr@lkq&{oBRG}0z{awg4EcJUkR&Cc}gvx|gDMs~j(Z2+0730qV`k!L*|8sEtK',
    'ZZ-',
    'w`)Q#@*|h%WKyuGH1i`v)`cuSH7Vat!THy+0t?X2lAI&N&4B$R>djILHfe8aJej*Q%Qqv}IiQ1y%af9AvkiG9~k?dO4HK85|{8+g',
    'BZnx|2y9uUNzm(EGZOCYBbFx~PGi?m|$La9;^rqKXEW1JXS!$`ln5F%D(M99rAsT%$dbR1px?Q1gs_a&HzRU-',
    'GSHKv~Pk{rAP+mFeS)gKV{=O<?*Xkw<t!zgENH7yrKEb8BsiAc6u&mbwrq&Kv>HvtUB;arO)f|>K)Q9~HjmGbHF-Tw#;x}@(?&?0',
    'I+xKefr+3uR)=f1_xP3h3*`%XYsh^DP0_1Pu;k!MAPfRI1eN&BphydD_)>q>d-',
    'j)888t_9s@S6beT{Y!@Gm$LyeSKAes~@24F6FNka?3W{XI9P+BfRh18nvRwwBf!x`*maOZ$<S_l<r%ymKJkga!oE43`GdiWJ3!A7',
    '#;ykjX!QV`mYveSn6+#6Zo(H0ej8k(f',
]
EXPECTED_MAIN_BYTES = 32232
EXPECTED_MAIN_SHA256 = "7996bed506ca5ade5663a58a9af5789a329b3f426dcd9787062ad98f22b07bb8"
TITLE_METRIC = "24/25 strict-future Top-30 replay cases; not an official LB score"

raw = zlib.decompress(base64.b85decode("".join(_AGENT_B85_PARTS).encode("ascii")))
assert len(raw) == EXPECTED_MAIN_BYTES
assert hashlib.sha256(raw).hexdigest() == EXPECTED_MAIN_SHA256
compile(raw, str(MAIN_PATH), "exec")
source = raw.decode("utf-8")
for forbidden in (
    "Kaito Fukami", "Yubo WANG", "Gbining", "THUNDER THUNDER",
    "CanonicalTeamNames", "CanonicalTeamIds", "SubmissionIds", "EpisodeId",
):
    assert forbidden not in source
MAIN_PATH.write_bytes(raw)

with tarfile.open(ARCHIVE_PATH, "w:gz") as archive:
    archive.add(MAIN_PATH, arcname="main.py")
with tarfile.open(ARCHIVE_PATH, "r:gz") as archive:
    assert archive.getnames() == ["main.py"]

spec = importlib.util.spec_from_file_location("public_v26_agent", MAIN_PATH)
module = importlib.util.module_from_spec(spec)
assert spec.loader is not None
spec.loader.exec_module(module)
assert len(module._SEAT0_ACTIONS) == 719
assert len(module._SEAT1_ACTIONS) == 719

import kaggle_environments
from kaggle_environments import make

notebook_engine_version = getattr(kaggle_environments, "__version__", "unknown")
env = make(
    "kaggriculture",
    configuration={"episodeSteps": 720, "seed": 260_810},
    debug=False,
)
schema_smoke = []
for seat, state in enumerate(env.reset()):
    observation = dict(state.observation)
    observation["player"] = seat
    action = module.agent(observation, env.configuration)
    assert set(action) == {"farmer", "hands", "market"}
    assert isinstance(action["farmer"], list)
    assert isinstance(action["hands"], list)
    assert isinstance(action["market"], list) and len(action["market"]) <= 10
    schema_smoke.append({
        "seat": seat,
        "farmer": action["farmer"],
        "hands": len(action["hands"]),
        "market_orders": len(action["market"]),
    })

print({
    "policy": "v26_seat_portfolio",
    "title_metric": TITLE_METRIC,
    "main_py": str(MAIN_PATH),
    "main_bytes": len(raw),
    "main_sha256": EXPECTED_MAIN_SHA256,
    "submission": str(ARCHIVE_PATH),
    "archive_members": ["main.py"],
    "research_engine_version": "1.32.6",
    "notebook_engine_version": notebook_engine_version,
    "research_exact_action_comparisons": 5760,
    "action_schema_smoke": schema_smoke,
    "ready": True,
})